export const Location = {
  UppsalaC: "Uppsala C",
  StockholmC: "Stockholm C",
  VästeråsC: "Västerås C",
  Enköping: "Enköping",
  Märsta: "Märsta",
  ArlandaC: "Arlanda C",
  Knivsta: "Knivsta",
  Bålsta: "Bålsta",
  Strängnäs: "Strängnäs",
  Eskilstuna: "Eskilstuna",
  SödertäljeC: "Södertälje C",
  Norrköping: "Norrköping",
  Linköping: "Linköping",
  Gävle: "Gävle",
  Umeå: "Umeå",
  Sundsvall: "Sundsvall",
  ÖrebroC: "Örebro C",
  Hallsberg: "Hallsberg",
  Växjö: "Växjö",
  Kalmar: "Kalmar",
  Jönköping: "Jönköping",
  Borås: "Borås",
  GöteborgC: "Göteborg C",
  MalmöC: "Malmö C",
  Lund: "Lund",
  HelsingborgC: "Helsingborg C",
  Kristianstad: "Kristianstad",
  Karlstad: "Karlstad",
  Karlskrona: "Karlskrona",
  Visby: "Visby",
  Östersund: "Östersund",
  Åre: "Åre",
  Kiruna: "Kiruna",
  Luleå: "Luleå",
  Boden: "Boden",
  Piteå: "Piteå",
  Skellefteå: "Skellefteå",
  Lycksele: "Lycksele",
  Arvidsjaur: "Arvidsjaur",
  Jokkmokk: "Jokkmokk",
  Gällivare: "Gällivare",
  Haparanda: "Haparanda",
  Riksgränsen: "Riksgränsen",
  Abisko: "Abisko",
  Narvik: "Narvik",
  Lofoten: "Lofoten",
  Tromsø: "Tromsø",
  Alta: "Alta",
  Hammerfest: "Hammerfest",
  Kirkenes: "Kirkenes",
} as const;
export type Location = typeof Location[keyof typeof Location];